version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Node version:"
      - node -v
      - npm -v

  pre_build:
    commands:
      - echo "Installing frontend dependencies..."
      - cd lost-and-found-frontend
      - npm install
      - cd ..

  build:
    commands:
      - echo "Building frontend..."
      - cd lost-and-found-frontend
      - npm run build
      - cd ..

  post_build:
    commands:
      - echo "Build Finished Successfully"

artifacts:
  files:
    - "**/*"
