version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing backend dependencies...
      - cd lost-and-found-frontend
      - npm install
 
  build:
    commands:
      - echo Building backend...
      - npm run build
 
  post_build:
    commands:
      - echo Deploying backend to ecr...
      - echo backend deployed successfully!
 
artifacts:
  files:
    - '**/*'
